<?php

return [
    'tasks' => [
        'file_migrate',
        'db_sync',

        'normalize:diagnosis',
        'normalize:country-codes-full',
        'normalize:endpoint',
        'normalize:tests',

        'ingest:excel-ui',
        'ingest:csv-ui',
        'ingest:json-ui',
        'ingest:api-endpoints',
        'ingest:web-scrapers',
        'ingest:log-system',
        'ingest:error-handling',
        'ingest:tests',

        'dogs:excel-import',
        'dogs:regno-advanced',
        'dogs:country-codes-full',
        'dogs:duplicate-detection',
        'dogs:merge-ui',
        'dogs:audit-module',

        'audit:ui',
        'audit:error-detection',
        'audit:fix-suggestions',
        'audit:fix-pipeline',
        'audit:export',
        'audit:tests',

        'events:meta-normalize',
        'events:ingest',
        'events:calendar-integration',
        'events:eventbrite',
        'events:google-events',
        'events:list-ui',
        'events:details-ui',
        'events:link-results',

        'breeding:coi-engine',
        'breeding:color-genetics',
        'breeding:health-risk',
        'breeding:plan-generator',
        'breeding:plan-ui',
        'breeding:genetics-ui',

        'i18n:keylist',
        'i18n:hu',
        'i18n:en',
        'i18n:de',
        'i18n:ro',
        'i18n:es',
        'i18n:pt',
        'i18n:switcher-ui',
        'i18n:auto-detect',

        'final:promotion-rules',
        'final:promotion-errors',
        'final:promotion-log',
        'final:promotion-rollback',
        'final:tests',

        'kennel:activity-check',
        'kennel:status-update',
        'kennel:audit-report',
        'kennel:ui',

        'clubs:db',
        'clubs:ui',
        'clubs:location',
        'clubs:activities',

        'pdf:layout',
        'pdf:3gen',
        'pdf:4gen',
        'pdf:color-modes',
        'pdf:export-button',
        'pdf:engine',

        'doctor:db',
        'doctor:clinic-db',
        'doctor:specialists',
        'doctor:location',
        'doctor:distance',
        'doctor:filters',
        'doctor:profiles',
        'doctor:call-route',
    ],
];